version: '2.2'
services:
    nginx:
        build:
            context: .
            dockerfile: docker/Dockerfile.nginx
            args:
                PHP_FPM_SERVER: php
                PHP_FPM_PORT: 9000
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - .:/var/www/
        networks:
            - backend

    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                XDEBUG: "true"
        volumes:
            - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./database/maxmind:/var/www/database/maxmind
        environment:
            APP_ENV: local
        ports:
            - "8080:8080"
        networks:
            - backend
        depends_on:
            - mysql

    redis:
        image: redis:5.0.6
        ports:
            - ${DOCKER_REDIS_EXTERNAL_PORT-6379}:6379
        networks:
            - backend

    mysql:
        image: mysql:8.0
        volumes:
            - mysqldb:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel_quizze
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
            - "3309:3306"
        command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        networks:
            - backend

    elasticsearch:
        build:
            context: ./docker/elasticsearch
            args:
                - ELK_VERSION=${ELK_VERSION}
        volumes:
            - laravelelastic:/usr/share/elasticsearch/data
        environment:
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - discovery.type=single-node
            - cluster.name=laradock-cluster
            - node.name=laradock-node
            - bootstrap.memory_lock=true
            - indices.id_field_data.enabled=true
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - backend

    kibana:
        image: docker.elastic.co/kibana/kibana:8.12.1
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - xpack.security.enabled=false
        networks:
            - backend


volumes:
    mysqldb:
        driver: local
    laravelelastic:
        driver: local

networks:
    backend:
        driver: "bridge"
